# Pushes up GitHub pages for semantics

name: pages
on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Download semantics.pdf to public directory
      - uses: actions/download-artifact@v3
        with:
          name: semantics
          path: public/

      # Copy over README.md to public directory
      - name: Build public directory
        run: cp README.md public/

      # Upload GitHub pages artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build

    permissions:
      pages: write      
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


        