# Compiles semantics.pdf and uploads it as an artifact

name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Download and unzip Typst
      - name: Download Typst
        run: |
          curl -L https://github.com/typst/typst/releases/download/v23-03-28/typst-x86_64-unknown-linux-gnu.tar.gz -o typst.tar.gz
          tar -xvf typst.tar.gz

      # Compile semantics.pdf
      - name: Compile Document
        run: ./typst-x86_64-unknown-linux-gnu/typst semantics.typ

      # Copy over semantics.pdf and README.md to public directory
      - name: Build public directory
        run: |
          mkdir public
          cp README.md public/index.md
          cp semantics.pdf public/

      # Upload GitHub pages artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public

  # Deploy GitHub pages site
  deploy:
    needs: build

    permissions:
      pages: write      
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

